version: '2'
services:
  ipfs:
    image: "ipfs/go-ipfs:latest"
    ports:
     - "8080:8080"
     - "4001:4001"
     - "5001:5001"
    volumes:
     - ../data/ipfs/data:/data/ipfs
     - ../data/ipfs/staging:/export
  testrpc:
    image: "openmined/sonar-testrpc:edge"
    ports:
      - "8545:8545"
